server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥 随便编写
    pubKeyPath: C:\\Users\\otsadmin\\Desktop\\me\\leyou\\leyou1\\auth-key\\rsa.pub # 公钥地址
    priKeyPath: C:\\Users\\otsadmin\\Desktop\\me\\leyou\\leyou1\\auth-key\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN