server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 47.92.36.107
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
leyou:
  jwt:
    pubKeyPath: D:\\Java\\idea\\leyou\\auth-key\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN