server:
  port: 8084
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 47.92.36.107
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka