server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3310/yun6?characterEncoding=utf8
    username: root
    password: wgbsql
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 47.92.36.107
    username: leyou
    password: leyou
    virtual-host: /leyou
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
leyou:
  jwt:
    pubKeyPath: D:\\Java\\idea\\leyou\\auth-key\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    datacenterId: 1
